# Generated by Django 5.0.6 on 2024-05-26 13:21

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4, 'Название должно быть не менее 4 символов'), django.core.validators.MaxLengthValidator(50, 'Название должно быть не более 50 символов')], verbose_name='Название')),
                ('anons', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100, 'Анонс должен быть не более 100 символов')], verbose_name='Анонс')),
                ('full_text', models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Статья должна быть не менее 50 символов')], verbose_name='Статья')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads_model/%Y%m%d/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
